### ISSUE TITLE
does influxdb-cli work with v0.9 of InfluxDB?

### ISSUE THREAD

**Issue by bear** [FGRibreau/influxdb-cli#19]
I have installed influxdb-cli but running it generates the following stacktrace:

foo:/opt/sbin# influxdb-cli -h 192.168.3.18
db> Connecting to http://192.168.3.18:8086/db/db ...

TypeError: Cannot read property 'status' of undefined
    at Request._callback (/usr/local/lib/node_modules/influxdb-cli/Client.js:138:13)
    at Request.self.callback (/usr/local/lib/node_modules/influxdb-cli/node_modules/request/request.js:129:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/influxdb-cli/node_modules/request/request.js:873:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/influxdb-cli/node_modules/request/request.js:824:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:938:16
    at process._tickCallback (node.js:419:13)

The InfluxDB admin interface is up and listening:
foo:/opt/sbin# telnet 192.168.3.18 8086
Trying 192.168.3.18...
Connected to 192.168.3.18.
Escape character is '^]'.
^]

telnet> quit
Connection closed.

OS is Ubuntu 14 LTS
NodeJS version is v0.10.30

thanks
##

**Comment by FGRibreau** [comment]
Hello @bear,

It seems InfluxDB 0.9 does not support status? Could you please check this?
