### ISSUE TITLE
influxdb-cli return error: /usr/bin/env: node: No such file or directory

### ISSUE THREAD

**Issue by shaiis** [FGRibreau/influxdb-cli#21]
version 0.9rc2
##

**Comment by FGRibreau** [comment]
- what OS are you using?
- what's the output of `which node` ?

**Comment by shaiis** [comment]
* ubuntu 14.04
* /usr/local/bin/node
node version is v0.10.35

**Comment by shaiis** [comment]
The OS is ubuntu 14.04.
which node: /usr/bin/node
node version: v0.10.37
I was missing node, i only installed npm.

now when I run the command I'm getting:

> influxdb-cli -d testdb -u test -p test
> testdb> Connecting to http://localhost:8086/db/testdb ...

TypeError: Cannot read property 'status' of undefined
    at Request._callback (/usr/local/lib/node_modules/influxdb-cli/Client.js:138:13)
    at Request.self.callback (/usr/local/lib/node_modules/influxdb-cli/node_modules/request/request.js:129:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/influxdb-cli/node_modules/request/request.js:873:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/influxdb-cli/node_modules/request/request.js:824:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)

**Comment by FGRibreau** [comment]
Hum, I'm sorry I don't maintain this project anymore, if just seem to be an issue with Client.js response handling, it should not be too hard to fix. Don't hesitate to send me a PR I will merge it :)
