### ISSUE TITLE
Crashes after each command.

### ISSUE THREAD

**Issue by phobos182** [FGRibreau/influxdb-cli#7]
After successfully executing a query, and returning results. Shows this error and exits.

Using NodeJS 0.8.14-1chl1~precise1

---

/usr/lib/node_modules/influxdb-cli/Cli.js:18
      setImmediate(startRepl.bind(null, fprompt, client, fPrint));
      ^
ReferenceError: setImmediate is not defined
    at /usr/lib/node_modules/influxdb-cli/Cli.js:18:7
    at Request._callback (/usr/lib/node_modules/influxdb-cli/Client.js:43:12)
    at Request.init.self.callback (/usr/lib/node_modules/influxdb-cli/node_modules/request/request.js:129:22)
    at Request.EventEmitter.emit (events.js:99:17)
    at Request.onResponse (/usr/lib/node_modules/influxdb-cli/node_modules/request/request.js:873:14)
    at Request.EventEmitter.emit (events.js:126:20)
    at IncomingMessage.Request.onResponse.buffer (/usr/lib/node_modules/influxdb-cli/node_modules/request/request.js:824:12)
    at IncomingMessage.EventEmitter.emit (events.js:126:20)
    at IncomingMessage._emitEnd (http.js:366:10)
    at HTTPParser.parserOnMessageComplete [as onMessageComplete](http.js:149:23)

**Comment by FGRibreau** [comment]
Hello Jeremy,

That's because InfluxDB-CLI requires NodeJS 0.10 (you can use [nvm](https://github.com/creationix/nvm) to easily manage/install multiple version of NodeJS), hope it helps!
